package com.fuyi.ecps.model;

public class EbBrand {

	private Long brandId;
	private String brandName;
	private String brandDesc;
	private String imgs;
	private String website;
	private Integer brandSort;
	
	
	
	
	public Long getBrandId() {
		return brandId;
	}
	public void setBrandId(Long brandId) {
		this.brandId = brandId;
	}
	public String getBrandName() {
		return brandName;
	}

	public void setBrandName(String brandName) {
		this.brandName = brandName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EB_BRAND.BRAND_DESC
	 * @return  the value of EB_BRAND.BRAND_DESC
	 * @mbggenerated  Sat Mar 28 09:52:29 CST 2015
	 */
	public String getBrandDesc() {
		return brandDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EB_BRAND.BRAND_DESC
	 * @param brandDesc  the value for EB_BRAND.BRAND_DESC
	 * @mbggenerated  Sat Mar 28 09:52:29 CST 2015
	 */
	public void setBrandDesc(String brandDesc) {
		this.brandDesc = brandDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EB_BRAND.IMGS
	 * @return  the value of EB_BRAND.IMGS
	 * @mbggenerated  Sat Mar 28 09:52:29 CST 2015
	 */
	public String getImgs() {
		return imgs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EB_BRAND.IMGS
	 * @param imgs  the value for EB_BRAND.IMGS
	 * @mbggenerated  Sat Mar 28 09:52:29 CST 2015
	 */
	public void setImgs(String imgs) {
		this.imgs = imgs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EB_BRAND.WEBSITE
	 * @return  the value of EB_BRAND.WEBSITE
	 * @mbggenerated  Sat Mar 28 09:52:29 CST 2015
	 */
	public String getWebsite() {
		return website;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EB_BRAND.WEBSITE
	 * @param website  the value for EB_BRAND.WEBSITE
	 * @mbggenerated  Sat Mar 28 09:52:29 CST 2015
	 */
	public void setWebsite(String website) {
		this.website = website;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EB_BRAND.BRAND_SORT
	 * @return  the value of EB_BRAND.BRAND_SORT
	 * @mbggenerated  Sat Mar 28 09:52:29 CST 2015
	 */
	public Integer getBrandSort() {
		return brandSort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EB_BRAND.BRAND_SORT
	 * @param brandSort  the value for EB_BRAND.BRAND_SORT
	 * @mbggenerated  Sat Mar 28 09:52:29 CST 2015
	 */
	public void setBrandSort(Integer brandSort) {
		this.brandSort = brandSort;
	}
}